env:
  RUBY_VERSION: 3.0

name: Rails tests
on: [push,pull_request]
jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
        working-directory: thanks_ants
      - name: Run tests
        run: bundle exec rspec
        working-directory: thanks_ants
